// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainPage_screen_init(void)
{
ui_MainPage = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainPage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NabBarMain = lv_obj_create(ui_MainPage);
lv_obj_remove_style_all(ui_NabBarMain);
lv_obj_set_width( ui_NabBarMain, 240);
lv_obj_set_height( ui_NabBarMain, 30);
lv_obj_clear_flag( ui_NabBarMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_NabBarMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NabBarMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconwifiNotconet = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconwifiNotconet, &ui_img_image_wifi_notconnect_png_png);
lv_obj_set_width( ui_ImiconwifiNotconet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconwifiNotconet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconwifiNotconet, 10 );
lv_obj_set_y( ui_ImiconwifiNotconet, 4 );
lv_obj_add_flag( ui_ImiconwifiNotconet, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconwifiNotconet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImiconwifiNotconet, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImiconwifiNotconet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconWarningMainPage = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconWarningMainPage, &ui_img_image_warning_icon_png_png);
lv_obj_set_width( ui_ImiconWarningMainPage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconWarningMainPage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconWarningMainPage, 85 );
lv_obj_set_y( ui_ImiconWarningMainPage, 2 );
lv_obj_add_flag( ui_ImiconWarningMainPage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconWarningMainPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImiconWarningMainPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImiconWarningMainPage, 250, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconMQTTconnet = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconMQTTconnet, &ui_img_image_mqtt_connect_png);
lv_obj_set_width( ui_ImiconMQTTconnet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconMQTTconnet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconMQTTconnet, 50 );
lv_obj_set_y( ui_ImiconMQTTconnet, 4 );
lv_obj_add_flag( ui_ImiconMQTTconnet, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconMQTTconnet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImiconMQTTconnet, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImiconMQTTconnet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconMQTTnotconnect = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconMQTTnotconnect, &ui_img_image_mqtt_notconnect_png_png);
lv_obj_set_width( ui_ImiconMQTTnotconnect, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconMQTTnotconnect, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconMQTTnotconnect, 50 );
lv_obj_set_y( ui_ImiconMQTTnotconnect, 4 );
lv_obj_add_flag( ui_ImiconMQTTnotconnect, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconMQTTnotconnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImiconMQTTnotconnect, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImiconMQTTnotconnect, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconWificonnect = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconWificonnect, &ui_img_image_wifi_isconect_png_png);
lv_obj_set_width( ui_ImiconWificonnect, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_ImiconWificonnect, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_ImiconWificonnect, 10 );
lv_obj_set_y( ui_ImiconWificonnect, 4 );
lv_obj_add_flag( ui_ImiconWificonnect, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconWificonnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImiconWificonnect, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImiconWificonnect, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconSettingAdmin = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconSettingAdmin, &ui_img_image_admin_png);
lv_obj_set_width( ui_ImiconSettingAdmin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconSettingAdmin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconSettingAdmin, 113 );
lv_obj_set_y( ui_ImiconSettingAdmin, 0 );
lv_obj_add_flag( ui_ImiconSettingAdmin, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconSettingAdmin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImiconSettingAdmin, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImiconSettingAdmin, 250, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImlogoMain = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImlogoMain, &ui_img_image_logo_wipay_png);
lv_obj_set_width( ui_ImlogoMain, LV_SIZE_CONTENT);  /// 79
lv_obj_set_height( ui_ImlogoMain, LV_SIZE_CONTENT);   /// 26
lv_obj_set_x( ui_ImlogoMain, 157 );
lv_obj_set_y( ui_ImlogoMain, 0 );
lv_obj_add_flag( ui_ImlogoMain, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImlogoMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CnMainDispayPay = lv_obj_create(ui_MainPage);
lv_obj_remove_style_all(ui_CnMainDispayPay);
lv_obj_set_width( ui_CnMainDispayPay, 240);
lv_obj_set_height( ui_CnMainDispayPay, 285);
lv_obj_set_x( ui_CnMainDispayPay, 0 );
lv_obj_set_y( ui_CnMainDispayPay, 12 );
lv_obj_set_align( ui_CnMainDispayPay, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CnMainDispayPay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CnMainDispayPay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CnMainDispayPay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LbPrice = lv_label_create(ui_CnMainDispayPay);
lv_obj_set_width( ui_LbPrice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbPrice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LbPrice, 104 );
lv_obj_set_y( ui_LbPrice, 254 );
lv_label_set_text(ui_LbPrice,"40");
lv_obj_set_style_text_color(ui_LbPrice, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LbPrice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LbPrice, &ui_font_Font40item, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImCurrency = lv_img_create(ui_CnMainDispayPay);
lv_img_set_src(ui_ImCurrency, &ui_img_image_baht_png_png);
lv_obj_set_width( ui_ImCurrency, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImCurrency, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImCurrency, 186 );
lv_obj_set_y( ui_ImCurrency, 251 );
lv_obj_add_flag( ui_ImCurrency, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImCurrency, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Cnlogoprompay = lv_obj_create(ui_CnMainDispayPay);
lv_obj_remove_style_all(ui_Cnlogoprompay);
lv_obj_set_width( ui_Cnlogoprompay, 240);
lv_obj_set_height( ui_Cnlogoprompay, 40);
lv_obj_clear_flag( ui_Cnlogoprompay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Cnlogoprompay, lv_color_hex(0x281788), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Cnlogoprompay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Imlogopromtpay = lv_img_create(ui_Cnlogoprompay);
lv_img_set_src(ui_Imlogopromtpay, &ui_img_image_logopromtpay_png);
lv_obj_set_width( ui_Imlogopromtpay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Imlogopromtpay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Imlogopromtpay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Imlogopromtpay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Imlogopromtpay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_CnMainDispayPay);
lv_obj_set_width( ui_Panel1, 200);
lv_obj_set_height( ui_Panel1, 200);
lv_obj_set_x( ui_Panel1, 21 );
lv_obj_set_y( ui_Panel1, 50 );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CnErorstate = lv_obj_create(ui_MainPage);
lv_obj_remove_style_all(ui_CnErorstate);
lv_obj_set_width( ui_CnErorstate, 240);
lv_obj_set_height( ui_CnErorstate, 285);
lv_obj_set_x( ui_CnErorstate, 0 );
lv_obj_set_y( ui_CnErorstate, 35 );
lv_obj_add_flag( ui_CnErorstate, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_CnErorstate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconWorning = lv_img_create(ui_CnErorstate);
lv_img_set_src(ui_ImiconWorning, &ui_img_image_imageworning_1_png);
lv_obj_set_width( ui_ImiconWorning, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconWorning, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconWorning, 35 );
lv_obj_set_y( ui_ImiconWorning, -9 );
lv_obj_add_flag( ui_ImiconWorning, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconWorning, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CnTextMasgEoR = lv_obj_create(ui_CnErorstate);
lv_obj_remove_style_all(ui_CnTextMasgEoR);
lv_obj_set_width( ui_CnTextMasgEoR, 211);
lv_obj_set_height( ui_CnTextMasgEoR, 109);
lv_obj_set_x( ui_CnTextMasgEoR, -1 );
lv_obj_set_y( ui_CnTextMasgEoR, 72 );
lv_obj_set_align( ui_CnTextMasgEoR, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CnTextMasgEoR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_outline_color(ui_CnTextMasgEoR, lv_color_hex(0xDC1313), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_CnTextMasgEoR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_CnTextMasgEoR, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_CnTextMasgEoR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LbHerde_Eror = lv_label_create(ui_CnTextMasgEoR);
lv_obj_set_width( ui_LbHerde_Eror, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbHerde_Eror, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LbHerde_Eror, -1 );
lv_obj_set_y( ui_LbHerde_Eror, -36 );
lv_obj_set_align( ui_LbHerde_Eror, LV_ALIGN_CENTER );
lv_label_set_text(ui_LbHerde_Eror,"Herder Eror");
lv_obj_set_style_text_font(ui_LbHerde_Eror, &ui_font_Font30item, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LbExplanatory_text = lv_label_create(ui_CnTextMasgEoR);
lv_obj_set_width( ui_LbExplanatory_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbExplanatory_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LbExplanatory_text, -17 );
lv_obj_set_y( ui_LbExplanatory_text, -8 );
lv_obj_set_align( ui_LbExplanatory_text, LV_ALIGN_CENTER );
lv_label_set_text(ui_LbExplanatory_text,"Explanatory text.............");

ui_ImiconWorning2 = lv_img_create(ui_CnErorstate);
lv_img_set_src(ui_ImiconWorning2, &ui_img_image_imageworning_1_copy_png);
lv_obj_set_width( ui_ImiconWorning2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconWorning2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconWorning2, 35 );
lv_obj_set_y( ui_ImiconWorning2, -9 );
lv_obj_add_flag( ui_ImiconWorning2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconWorning2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);

}
