// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainPage_screen_init(void)
{
ui_MainPage = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NabBarMain = lv_obj_create(ui_MainPage);
lv_obj_remove_style_all(ui_NabBarMain);
lv_obj_set_width( ui_NabBarMain, 240);
lv_obj_set_height( ui_NabBarMain, 35);
lv_obj_clear_flag( ui_NabBarMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_NabBarMain, lv_color_hex(0x6DE3C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NabBarMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconwifiNotconet = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconwifiNotconet, &ui_img_image_wifi_notconnect_png_png);
lv_obj_set_width( ui_ImiconwifiNotconet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconwifiNotconet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconwifiNotconet, 19 );
lv_obj_set_y( ui_ImiconwifiNotconet, 6 );
lv_obj_add_flag( ui_ImiconwifiNotconet, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconwifiNotconet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconwifiConnet = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconwifiConnet, &ui_img_image_warning_icon_png_png);
lv_obj_set_width( ui_ImiconwifiConnet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconwifiConnet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImiconwifiConnet, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImiconwifiConnet, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconwifiConnet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconMQTTconnet = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconMQTTconnet, &ui_img_image_mqtt_connect_png);
lv_obj_set_width( ui_ImiconMQTTconnet, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconMQTTconnet, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconMQTTconnet, 63 );
lv_obj_set_y( ui_ImiconMQTTconnet, 6 );
lv_obj_add_flag( ui_ImiconMQTTconnet, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconMQTTconnet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconMQTTnotconnect = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconMQTTnotconnect, &ui_img_image_mqtt_notconnect_png_png);
lv_obj_set_width( ui_ImiconMQTTnotconnect, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconMQTTnotconnect, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconMQTTnotconnect, 63 );
lv_obj_set_y( ui_ImiconMQTTnotconnect, 6 );
lv_obj_add_flag( ui_ImiconMQTTnotconnect, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconMQTTnotconnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconWificonnect = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconWificonnect, &ui_img_image_wifi_isconect_png_png);
lv_obj_set_width( ui_ImiconWificonnect, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_ImiconWificonnect, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_ImiconWificonnect, 19 );
lv_obj_set_y( ui_ImiconWificonnect, 6 );
lv_obj_add_flag( ui_ImiconWificonnect, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconWificonnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconSettingAdmin = lv_img_create(ui_NabBarMain);
lv_img_set_src(ui_ImiconSettingAdmin, &ui_img_image_admin_png);
lv_obj_set_width( ui_ImiconSettingAdmin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconSettingAdmin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconSettingAdmin, 160 );
lv_obj_set_y( ui_ImiconSettingAdmin, 2 );
lv_obj_add_flag( ui_ImiconSettingAdmin, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconSettingAdmin, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CnMainDispayPay = lv_obj_create(ui_MainPage);
lv_obj_remove_style_all(ui_CnMainDispayPay);
lv_obj_set_width( ui_CnMainDispayPay, 240);
lv_obj_set_height( ui_CnMainDispayPay, 280);
lv_obj_set_x( ui_CnMainDispayPay, 0 );
lv_obj_set_y( ui_CnMainDispayPay, 20 );
lv_obj_set_align( ui_CnMainDispayPay, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CnMainDispayPay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CnMainDispayPay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CnMainDispayPay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CnQrpromtPay = lv_obj_create(ui_CnMainDispayPay);
lv_obj_remove_style_all(ui_CnQrpromtPay);
lv_obj_set_width( ui_CnQrpromtPay, 200);
lv_obj_set_height( ui_CnQrpromtPay, 209);
lv_obj_set_x( ui_CnQrpromtPay, 20 );
lv_obj_set_y( ui_CnQrpromtPay, 20 );
lv_obj_clear_flag( ui_CnQrpromtPay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CnQrpromtPay, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CnQrpromtPay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CnQrpromtPay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_CnQrpromtPay, lv_color_hex(0x212176), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_CnQrpromtPay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_CnQrpromtPay, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_CnQrpromtPay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_CnQrpromtPay);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 200);
lv_obj_set_height( ui_Container5, 27);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Container5, &ui_img_image_logopayment_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_PanelShowQR = lv_obj_create(ui_CnQrpromtPay);
lv_obj_set_width( ui_PanelShowQR, 150);
lv_obj_set_height( ui_PanelShowQR, 150);
lv_obj_set_x( ui_PanelShowQR, 25 );
lv_obj_set_y( ui_PanelShowQR, 43 );
lv_obj_clear_flag( ui_PanelShowQR, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelShowQR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelShowQR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_LbnamePrice = lv_label_create(ui_CnMainDispayPay);
lv_obj_set_width( ui_LbnamePrice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbnamePrice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LbnamePrice, 22 );
lv_obj_set_y( ui_LbnamePrice, 249 );
lv_label_set_text(ui_LbnamePrice,"Price :");
lv_obj_set_style_text_font(ui_LbnamePrice, &ui_font_Font20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LbPrice = lv_label_create(ui_CnMainDispayPay);
lv_obj_set_width( ui_LbPrice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbPrice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LbPrice, 104 );
lv_obj_set_y( ui_LbPrice, 243 );
lv_label_set_text(ui_LbPrice,"40");
lv_obj_set_style_text_color(ui_LbPrice, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LbPrice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LbPrice, &ui_font_Font40item, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImCurrency = lv_img_create(ui_CnMainDispayPay);
lv_img_set_src(ui_ImCurrency, &ui_img_image_baht_png_png);
lv_obj_set_width( ui_ImCurrency, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImCurrency, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImCurrency, 188 );
lv_obj_set_y( ui_ImCurrency, 242 );
lv_obj_add_flag( ui_ImCurrency, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImCurrency, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CnErorstate = lv_obj_create(ui_MainPage);
lv_obj_remove_style_all(ui_CnErorstate);
lv_obj_set_width( ui_CnErorstate, 240);
lv_obj_set_height( ui_CnErorstate, 285);
lv_obj_set_x( ui_CnErorstate, 0 );
lv_obj_set_y( ui_CnErorstate, 35 );
lv_obj_add_flag( ui_CnErorstate, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_CnErorstate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconWorning = lv_img_create(ui_CnErorstate);
lv_img_set_src(ui_ImiconWorning, &ui_img_image_imageworning_1_png);
lv_obj_set_width( ui_ImiconWorning, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconWorning, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconWorning, 35 );
lv_obj_set_y( ui_ImiconWorning, -9 );
lv_obj_add_flag( ui_ImiconWorning, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconWorning, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CnTextMasgEoR = lv_obj_create(ui_CnErorstate);
lv_obj_remove_style_all(ui_CnTextMasgEoR);
lv_obj_set_width( ui_CnTextMasgEoR, 211);
lv_obj_set_height( ui_CnTextMasgEoR, 109);
lv_obj_set_x( ui_CnTextMasgEoR, -1 );
lv_obj_set_y( ui_CnTextMasgEoR, 72 );
lv_obj_set_align( ui_CnTextMasgEoR, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CnTextMasgEoR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_outline_color(ui_CnTextMasgEoR, lv_color_hex(0xDC1313), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_CnTextMasgEoR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_CnTextMasgEoR, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_CnTextMasgEoR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LbHerde_Eror = lv_label_create(ui_CnTextMasgEoR);
lv_obj_set_width( ui_LbHerde_Eror, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbHerde_Eror, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LbHerde_Eror, -1 );
lv_obj_set_y( ui_LbHerde_Eror, -36 );
lv_obj_set_align( ui_LbHerde_Eror, LV_ALIGN_CENTER );
lv_label_set_text(ui_LbHerde_Eror,"Herder Eror");
lv_obj_set_style_text_font(ui_LbHerde_Eror, &ui_font_Font30item, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LbExplanatory_text = lv_label_create(ui_CnTextMasgEoR);
lv_obj_set_width( ui_LbExplanatory_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LbExplanatory_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LbExplanatory_text, -17 );
lv_obj_set_y( ui_LbExplanatory_text, -8 );
lv_obj_set_align( ui_LbExplanatory_text, LV_ALIGN_CENTER );
lv_label_set_text(ui_LbExplanatory_text,"Explanatory text.............");

lv_obj_add_event_cb(ui_PanelShowQR, ui_event_PanelShowQR, LV_EVENT_ALL, NULL);

}
