// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_WorckingPage1_screen_init(void)
{
ui_WorckingPage1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WorckingPage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NabBarWorkingPage = lv_obj_create(ui_WorckingPage1);
lv_obj_remove_style_all(ui_NabBarWorkingPage);
lv_obj_set_width( ui_NabBarWorkingPage, 240);
lv_obj_set_height( ui_NabBarWorkingPage, 35);
lv_obj_clear_flag( ui_NabBarWorkingPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_NabBarWorkingPage, lv_color_hex(0x6DE3C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NabBarWorkingPage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImiconwifiNotconetWorkingPage = lv_img_create(ui_NabBarWorkingPage);
lv_img_set_src(ui_ImiconwifiNotconetWorkingPage, &ui_img_image_wifi_notconnect_png_png);
lv_obj_set_width( ui_ImiconwifiNotconetWorkingPage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconwifiNotconetWorkingPage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconwifiNotconetWorkingPage, 19 );
lv_obj_set_y( ui_ImiconwifiNotconetWorkingPage, 6 );
lv_obj_add_flag( ui_ImiconwifiNotconetWorkingPage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconwifiNotconetWorkingPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconwifiConnetWorkingPage = lv_img_create(ui_NabBarWorkingPage);
lv_img_set_src(ui_ImiconwifiConnetWorkingPage, &ui_img_image_warning_icon_png_png);
lv_obj_set_width( ui_ImiconwifiConnetWorkingPage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconwifiConnetWorkingPage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImiconwifiConnetWorkingPage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImiconwifiConnetWorkingPage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconwifiConnetWorkingPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconMQTTconnetWorkingPage = lv_img_create(ui_NabBarWorkingPage);
lv_img_set_src(ui_ImiconMQTTconnetWorkingPage, &ui_img_image_mqtt_connect_png);
lv_obj_set_width( ui_ImiconMQTTconnetWorkingPage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconMQTTconnetWorkingPage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconMQTTconnetWorkingPage, 63 );
lv_obj_set_y( ui_ImiconMQTTconnetWorkingPage, 6 );
lv_obj_add_flag( ui_ImiconMQTTconnetWorkingPage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconMQTTconnetWorkingPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconMQTTnotconnectWorkingPage = lv_img_create(ui_NabBarWorkingPage);
lv_img_set_src(ui_ImiconMQTTnotconnectWorkingPage, &ui_img_image_mqtt_notconnect_png_png);
lv_obj_set_width( ui_ImiconMQTTnotconnectWorkingPage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconMQTTnotconnectWorkingPage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconMQTTnotconnectWorkingPage, 63 );
lv_obj_set_y( ui_ImiconMQTTnotconnectWorkingPage, 6 );
lv_obj_add_flag( ui_ImiconMQTTnotconnectWorkingPage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconMQTTnotconnectWorkingPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconWificonnectWorkingPage = lv_img_create(ui_NabBarWorkingPage);
lv_img_set_src(ui_ImiconWificonnectWorkingPage, &ui_img_image_wifi_isconect_png_png);
lv_obj_set_width( ui_ImiconWificonnectWorkingPage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_ImiconWificonnectWorkingPage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_ImiconWificonnectWorkingPage, 19 );
lv_obj_set_y( ui_ImiconWificonnectWorkingPage, 6 );
lv_obj_add_flag( ui_ImiconWificonnectWorkingPage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconWificonnectWorkingPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImiconSettingAdminWorkingPage = lv_img_create(ui_NabBarWorkingPage);
lv_img_set_src(ui_ImiconSettingAdminWorkingPage, &ui_img_image_admin_png);
lv_obj_set_width( ui_ImiconSettingAdminWorkingPage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImiconSettingAdminWorkingPage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImiconSettingAdminWorkingPage, 160 );
lv_obj_set_y( ui_ImiconSettingAdminWorkingPage, 2 );
lv_obj_add_flag( ui_ImiconSettingAdminWorkingPage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImiconSettingAdminWorkingPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CnWorkingPage = lv_obj_create(ui_WorckingPage1);
lv_obj_remove_style_all(ui_CnWorkingPage);
lv_obj_set_width( ui_CnWorkingPage, 240);
lv_obj_set_height( ui_CnWorkingPage, 285);
lv_obj_set_x( ui_CnWorkingPage, 0 );
lv_obj_set_y( ui_CnWorkingPage, 35 );
lv_obj_clear_flag( ui_CnWorkingPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_CnWorkingPage);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 0 );
lv_obj_set_y( ui_Label6, 117 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Washing working");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xDDAD51), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_Font30item, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImMachine = lv_img_create(ui_CnWorkingPage);
lv_img_set_src(ui_ImMachine, &ui_img_image_rectangle_png);
lv_obj_set_width( ui_ImMachine, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImMachine, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImMachine, 33 );
lv_obj_set_y( ui_ImMachine, 16 );
lv_obj_add_flag( ui_ImMachine, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImMachine, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImTark = lv_img_create(ui_CnWorkingPage);
lv_img_set_src(ui_ImTark, &ui_img_image_tank__png);
lv_obj_set_width( ui_ImTark, 194);
lv_obj_set_height( ui_ImTark, 256);
lv_obj_set_x( ui_ImTark, 23 );
lv_obj_set_y( ui_ImTark, 5 );
lv_obj_add_flag( ui_ImTark, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImTark, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_WorckingPage1, ui_event_WorckingPage1, LV_EVENT_ALL, NULL);

}
