// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Display_statusWorking_Animation( lv_obj_t *TargetObject, int delay);
void DisplayErorAnima_Animation( lv_obj_t *TargetObject, int delay);
void DisplayErorIcon_Animation( lv_obj_t *TargetObject, int delay);

void Message_text_Eror(const char *HerderEror,const char *Text_details);
void Update_Price(const char *Amout);
void Display_Nab_bar_Network(bool statustWifi,bool statustMQTT);
void Display_Nab_bar_warning(bool statusWorining);
void Display_Nab_bar_Config_Wifi(bool statusConfigWifi);
void create_qrcode(lv_obj_t *parent,lv_obj_t *qrcode, const char *text);
// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
extern lv_obj_t *ui_MainPage;
extern lv_obj_t *ui_NabBarMain;
extern lv_obj_t *ui_ImiconwifiNotconet;
extern lv_obj_t *ui_ImiconWarningMainPage;
extern lv_obj_t *ui_ImiconMQTTconnet;
extern lv_obj_t *ui_ImiconMQTTnotconnect;
extern lv_obj_t *ui_ImiconWificonnect;
extern lv_obj_t *ui_ImiconSettingAdmin;
extern lv_obj_t *ui_ImlogoMain;
extern lv_obj_t *ui_CnMainDispayPay;
extern lv_obj_t *ui_LbPrice;
extern lv_obj_t *ui_ImCurrency;
extern lv_obj_t *ui_Cnlogoprompay;
extern lv_obj_t *ui_Imlogopromtpay;
void ui_event_Panel1( lv_event_t * e);
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_CnErorstate;
extern lv_obj_t *ui_ImiconWorning;
extern lv_obj_t *ui_CnTextMasgEoR;
extern lv_obj_t *ui_LbHerde_Eror;
extern lv_obj_t *ui_LbExplanatory_text;
extern lv_obj_t *ui_ImiconWorning2;
// SCREEN: ui_WorckingPage1
void ui_WorckingPage1_screen_init(void);
void ui_event_WorckingPage1( lv_event_t * e);
extern lv_obj_t *ui_WorckingPage1;
extern lv_obj_t *ui_NabBarWorkingPage;
extern lv_obj_t *ui_ImiconwifiNotconetWorkingPage;
extern lv_obj_t *ui_ImiconwifiConnetWorkingPage;
extern lv_obj_t *ui_ImiconMQTTconnetWorkingPage;
extern lv_obj_t *ui_ImiconMQTTnotconnectWorkingPage;
extern lv_obj_t *ui_ImiconWificonnectWorkingPage;
extern lv_obj_t *ui_ImiconSettingAdminWorkingPage;
extern lv_obj_t *ui_ImlogoMain2;
extern lv_obj_t *ui_CnWorkingPage;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_ImMachine;
extern lv_obj_t *ui_ImTark;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_image_wifi_notconnect_png_png);   // assets/Image/Wifi_notconnect.png.png
LV_IMG_DECLARE( ui_img_image_warning_icon_png_png);   // assets/Image/Warning_icon.png.png
LV_IMG_DECLARE( ui_img_image_mqtt_connect_png);   // assets/Image/MQTT_Connect.png
LV_IMG_DECLARE( ui_img_image_mqtt_notconnect_png_png);   // assets/Image/MQTT_Notconnect.png.png
LV_IMG_DECLARE( ui_img_image_wifi_isconect_png_png);   // assets/Image/Wifi_isconect.png.png
LV_IMG_DECLARE( ui_img_image_admin_png);   // assets/Image/Admin.png
LV_IMG_DECLARE( ui_img_image_logo_wipay_png);   // assets/Image/logo_wipay.png
LV_IMG_DECLARE( ui_img_image_baht_png_png);   // assets/Image/Baht.png.png
LV_IMG_DECLARE( ui_img_image_logopromtpay_png);   // assets/Image/logoPromtpay.png
LV_IMG_DECLARE( ui_img_image_imageworning_1_png);   // assets/Image/imageWorning 1.png
LV_IMG_DECLARE( ui_img_image_imageworning_1_copy_png);   // assets/Image/imageWorning 1 copy.png
LV_IMG_DECLARE( ui_img_image_rectangle_png);   // assets/Image/Rectangle.png
LV_IMG_DECLARE( ui_img_image_tank__png);   // assets/Image/tank .png


LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Font20);
LV_FONT_DECLARE( ui_font_Font30);
LV_FONT_DECLARE( ui_font_Font30item);
LV_FONT_DECLARE( ui_font_Font36item);
LV_FONT_DECLARE( ui_font_Font40item);
LV_FONT_DECLARE( ui_font_Font50);
LV_FONT_DECLARE( ui_font_Font60);
LV_FONT_DECLARE( ui_font_Font60b);
LV_FONT_DECLARE( ui_font_Thaifont50);
LV_FONT_DECLARE( ui_font_ThaifontNoto20);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
