// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Display_statusWorking_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
lv_obj_t *ui_MainPage;
lv_obj_t *ui_NabBarMain;
lv_obj_t *ui_ImiconwifiNotconet;
lv_obj_t *ui_ImiconwifiConnet;
lv_obj_t *ui_ImiconMQTTconnet;
lv_obj_t *ui_ImiconMQTTnotconnect;
lv_obj_t *ui_ImiconWificonnect;
lv_obj_t *ui_ImiconSettingAdmin;
lv_obj_t *ui_CnMainDispayPay;
lv_obj_t *ui_CnQrpromtPay;
lv_obj_t *ui_Container5;
void ui_event_PanelShowQR( lv_event_t * e);
lv_obj_t *ui_PanelShowQR;
lv_obj_t *ui_LbScanQR;
lv_obj_t *ui_LbnamePrice;
lv_obj_t *ui_LbPrice;
lv_obj_t *ui_ImCurrency;
lv_obj_t *ui_CnErorstate;
lv_obj_t *ui_ImiconWorning;
lv_obj_t *ui_CnTextMasgEoR;
lv_obj_t *ui_LbHerde_Eror;
lv_obj_t *ui_LbExplanatory_text;


// SCREEN: ui_WorckingPage1
void ui_WorckingPage1_screen_init(void);
void ui_event_WorckingPage1( lv_event_t * e);
lv_obj_t *ui_WorckingPage1;
lv_obj_t *ui_NabBarWorkingPage;
lv_obj_t *ui_ImiconwifiNotconetWorkingPage;
lv_obj_t *ui_ImiconwifiConnetWorkingPage;
lv_obj_t *ui_ImiconMQTTconnetWorkingPage;
lv_obj_t *ui_ImiconMQTTnotconnectWorkingPage;
lv_obj_t *ui_ImiconWificonnectWorkingPage;
lv_obj_t *ui_ImiconSettingAdminWorkingPage;
lv_obj_t *ui_CnWorkingPage;
lv_obj_t *ui_Label6;
lv_obj_t *ui_ImMachine;
lv_obj_t *ui_ImTark;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_imageworning_[1] = {&ui_img_image_imageworning_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Display_statusWorking_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_PanelShowQR( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      On_pressd_config_Wifi( e );
      _ui_screen_change( &ui_WorckingPage1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_WorckingPage1_screen_init);
}
}
void ui_event_WorckingPage1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      Display_statusWorking_Animation(ui_ImTark, 0);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainPage_screen_init();
ui_WorckingPage1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainPage);
}
